name: Build and Upload Game.wasm

on:
  push:
    branches: [ "stable-wasm" ]
  pull_request:
    branches: [ "stable-wasm" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Emscripten
        uses: emscripten-core/setup-emsdk@v16

      - name: Configure CMake
        run: emcmake cmake -B build -DCMAKE_BUILD_TYPE=Release -DRETRO_REVISION=2

      - name: Build Project
        run: cmake --build build --parallel

      - name: Upload Game.wasm
        uses: actions/upload-artifact@v4
        with:
          name: game-wasm
          path: build/Addendum.wasm
